/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ui;

import com.google.inject.Injector;
import fr.mleduc.xtext.xbase.specialized.ui.internal.SpecializedActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XbaseSpecializedExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpecializedActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpecializedActivator activator = SpecializedActivator.getInstance();
		return activator != null ? activator.getInjector(SpecializedActivator.FR_MLEDUC_XTEXT_XBASE_SPECIALIZED_XBASESPECIALIZED) : null;
	}

}
