/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XbaseSpecializedAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/mleduc/xtext/xbase/specialized/parser/antlr/internal/InternalXbaseSpecialized.tokens");
	}
}
