/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.parser.antlr;

import com.google.inject.Inject;
import fr.mleduc.xtext.xbase.specialized.parser.antlr.internal.InternalXbaseSpecializedParser;
import fr.mleduc.xtext.xbase.specialized.services.XbaseSpecializedGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XbaseSpecializedParser extends AbstractAntlrParser {

	@Inject
	private XbaseSpecializedGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXbaseSpecializedParser createParser(XtextTokenStream stream) {
		return new InternalXbaseSpecializedParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public XbaseSpecializedGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XbaseSpecializedGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
