/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ui;

import fr.mleduc.xtext.xbase.specialized.ui.AbstractXbaseSpecializedUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XbaseSpecializedUiModule extends AbstractXbaseSpecializedUiModule {
  public XbaseSpecializedUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
