/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.validation;

import fr.mleduc.xtext.xbase.specialized.validation.AbstractXbaseSpecializedValidator;
import org.eclipse.xtext.xbase.XExpression;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XbaseSpecializedValidator extends AbstractXbaseSpecializedValidator {
  @Override
  protected boolean isValueExpectedRecursive(final XExpression expr) {
    return super.isValueExpectedRecursive(expr);
  }
}
