/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ui.contentassist;

import fr.mleduc.xtext.xbase.specialized.ui.contentassist.AbstractXbaseSpecializedProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XbaseSpecializedProposalProvider extends AbstractXbaseSpecializedProposalProvider {
}
