/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XbaseSpecializedStandaloneSetup extends XbaseSpecializedStandaloneSetupGenerated {

	def static void doSetup() {
		new XbaseSpecializedStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
