/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractXbaseSpecializedScopeProvider extends XbaseBatchScopeProvider {
}
