/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ide


/**
 * Use this class to register ide components.
 */
class XbaseSpecializedIdeModule extends AbstractXbaseSpecializedIdeModule {
}
