/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized;

import fr.mleduc.xtext.xbase.specialized.AbstractXbaseSpecializedRuntimeModule;
import fr.mleduc.xtext.xbase.specialized.compiler.XbaseSpecializedCompiler;
import fr.mleduc.xtext.xbase.specialized.controlflow.XbaseSpecializedExitComputer;
import fr.mleduc.xtext.xbase.specialized.interpreter.XbaseSpecializedInterpreter;
import fr.mleduc.xtext.xbase.specialized.types.XbaseSpecializedTypeComputer;
import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.controlflow.IEarlyExitComputer;
import org.eclipse.xtext.xbase.interpreter.IExpressionInterpreter;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XbaseSpecializedRuntimeModule extends AbstractXbaseSpecializedRuntimeModule {
  public Class<? extends ITypeComputer> bindITypeComputer() {
    return XbaseSpecializedTypeComputer.class;
  }
  
  public Class<? extends XbaseCompiler> bindXbaseCompiler() {
    return XbaseSpecializedCompiler.class;
  }
  
  @Override
  public Class<? extends IExpressionInterpreter> bindIExpressionInterpreter() {
    return XbaseSpecializedInterpreter.class;
  }
  
  public Class<? extends IEarlyExitComputer> bindIEarlyExitComputer() {
    return XbaseSpecializedExitComputer.class;
  }
}
