/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized;

import fr.mleduc.xtext.xbase.specialized.XbaseSpecializedStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XbaseSpecializedStandaloneSetup extends XbaseSpecializedStandaloneSetupGenerated {
  public static void doSetup() {
    new XbaseSpecializedStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
