/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.xbaseSpecialized;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.XbaseSpecializedPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends XBlockExpression
{
} // Model
