/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.xbaseSpecialized;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.xtext.xbase.XbasePackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.XbaseSpecializedFactory
 * @model kind="package"
 * @generated
 */
public interface XbaseSpecializedPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xbaseSpecialized";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mleduc.fr/xtext/xbase/specialized/XbaseSpecialized";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xbaseSpecialized";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XbaseSpecializedPackage eINSTANCE = fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.XbaseSpecializedPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.ModelImpl
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.XbaseSpecializedPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int MODEL__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.DownImpl <em>Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.DownImpl
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.XbaseSpecializedPackageImpl#getDown()
   * @generated
   */
  int DOWN = 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__EXPRESSION = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.Down <em>Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Down</em>'.
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.Down
   * @generated
   */
  EClass getDown();

  /**
   * Returns the meta object for the containment reference '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.Down#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.Down#getExpression()
   * @see #getDown()
   * @generated
   */
  EReference getDown_Expression();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XbaseSpecializedFactory getXbaseSpecializedFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.ModelImpl
     * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.XbaseSpecializedPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.DownImpl <em>Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.DownImpl
     * @see fr.mleduc.xtext.xbase.specialized.xbaseSpecialized.impl.XbaseSpecializedPackageImpl#getDown()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDown();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOWN__EXPRESSION = eINSTANCE.getDown_Expression();

  }

} //XbaseSpecializedPackage
