/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.validation

import org.eclipse.xtext.xbase.XExpression

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XbaseSpecializedValidator extends AbstractXbaseSpecializedValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					XbaseSpecializedPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	
	override protected isValueExpectedRecursive(XExpression expr) {
		return super.isValueExpectedRecursive(expr) 
	}
}
