/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class XbaseSpecializedLabelProvider extends XbaseLabelProvider {
  @Inject
  public XbaseSpecializedLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
