/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.mleduc.xtext.xbase.specialized.XbaseSpecializedRuntimeModule;
import fr.mleduc.xtext.xbase.specialized.XbaseSpecializedStandaloneSetup;
import fr.mleduc.xtext.xbase.specialized.ide.XbaseSpecializedIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XbaseSpecializedIdeSetup extends XbaseSpecializedStandaloneSetup {
  @Override
  public Injector createInjector() {
    XbaseSpecializedRuntimeModule _xbaseSpecializedRuntimeModule = new XbaseSpecializedRuntimeModule();
    XbaseSpecializedIdeModule _xbaseSpecializedIdeModule = new XbaseSpecializedIdeModule();
    return Guice.createInjector(Modules2.mixin(_xbaseSpecializedRuntimeModule, _xbaseSpecializedIdeModule));
  }
}
