/**
 * generated by Xtext 2.14.0
 */
package fr.mleduc.xtext.xbase.specialized.ide;

import fr.mleduc.xtext.xbase.specialized.ide.AbstractXbaseSpecializedIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XbaseSpecializedIdeModule extends AbstractXbaseSpecializedIdeModule {
}
